title: IT-блог
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://future-imperfect.kaptn.ru" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Viktoriya Kapitonenko'
  last_name: 'Kapitonenko'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  kaptn3  
  email: vika@kaptn.ru
  vk_id: id201664979
  telegram_name: vikapitoshka 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


